### PR TITLE
Remove <2.0 cryptography constraint

### PR DESCRIPTION
**Pull request by tomgoren**
The [update to Cryptography today](https://cryptography.io/en/latest/changelog/#id1) broke our builds.

Is this something you would consider merging posthaste? It would be *very* appreciated!

I tested `get` and `put` commands via the `credstash` CLI to verify that this can be done safely. I'm uncertain though if this change has further implications. I just assumed that it is some legacy holdover.

Thanks!

### CODE REVIEW

**Comment by tomgoren** [comment]
FWIW - the current requirements clash in projects that use PyOpenSSL because: https://github.com/pyca/pyopenssl/blob/master/setup.py#L99

**Comment by tomgoren** [comment]
Thank you @alex-luminal ❤️

**Comment by jessemyers** [comment]
Any estimate on when to expect a new release with this in it?

**Comment by captn3m0** [comment]
Waiting for a fix. When is this planned for a release?

**Pull request merged**
