### PR TITLE
Start of Basic Unit Testing of Utility functions

### PR DESCRIPTION
**Pull request by vccabral**
@alex-luminal I am still working on figuring out getting the travis yml to run the tests. I will let you know when that is done but we should see the test verifications in the merge request at that point.

### CODE REVIEW

**Comment by vccabral** [comment]
selfie-0
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Comment by vccabral** [comment]
@alex-luminal I turned on travis for my fork. You might need to turn on travis for your upstream for the travis reports to start showing up. Not sure though. Let me see if the internet knows about these things.

**Comment by vccabral** [comment]
@alex-luminal you need to activate travisci for this repo on your upstream fork. I have everything running and working on my downstream fork. 

PR feedback is appreciated.

**Comment by alex-luminal** [comment]
Looks great! If you move your tests into a `tests/` directory, then we can just do `nosetests .` from the root, and it'll run them (and the travis python environment comes with nose :) ).

**Comment by vccabral** [comment]
@alex-luminal cool, I tried to do just that but maybe there is something I am not understanding. 

```
mkdir tests
mv runtests.py tests/runtests.py
pip install -r requirements.txt
pip install nose
nosetests .
```

gives me
```

----------------------------------------------------------------------
Ran 0 tests in 0.001s

OK
```

**Comment by vccabral** [comment]
travis file now has 

```
nosetests tests/*.py
```

**Pull request merged**
