### PR TITLE
Fix listSecrets only showing the first page of Scan results

### PR DESCRIPTION
**Pull request by pm990320**
We recently experienced problems with credstash at scale, that some secrets weren't being returned.

Saw this was already a reported probelm in (#109) and have created pull request with our changes.

### CODE REVIEW

**Comment by williamsbdev** [comment]
@pm990320 - First of all, thanks for writing the fix for this!

@alex-luminal / @a5an0 (not sure which account you use more often) or @dom-at-fugue / @domZippilli (not sure which account you use more often) - We would love to see this merged and published up!

Is there anything I can do to help this project? I've noticed a lack of test coverage. Would it allow us to move more quickly if we had more test coverage of the project?

**Comment by evanstachowiak** [comment]
I would love to see this merged as well, encountering the same problem.

**Comment by grahamhar** [comment]
Just noticed this after I raised my own PR, closing that as it is a duplicate of this.

**Comment by wayne-luminal** [comment]
@pm990320 Thank you so much for the fix. Sorry it's taken so long to get back to you. I'm going through all the PRs now.

**Comment by wayne-luminal** [comment]
Thanks for the bug fix @pm990320! I'm merging this in and will get it out into the next release.

@williamsbdev I agree that there could be more test coverage. I'm working on the next minor version as well as a major version that will come later with some refactoring and other new features submitted by other PRs. I'm hoping to increase test coverage but please submit PRs adding tests. That would be fantastic!

**Pull request merged**
